### ISSUE TITLE
CSS Preprocessor

### ISSUE THREAD

**Issue by SevereOverfl0w** [SevereOverfl0w/Unicorn-UI-Kit#2]
Less, Sass, Stylus or maybe http://www.myth.io/

Other suggestions open.
I suggest we try and keep to 100% node, (as in, let's use Libsass if we go down that route.) I don't want to juggle Sass gem versions.

---

**Comment by connor4312** [comment]
I'd go for Sass and Libsass.

**Comment by LordFren** [comment]
Less style pre processing - but it should have a clean css so anyone can get in and work

**Comment by LordFren** [comment]
16 column grid system - more flexible than bootstrap
It should be desktop down when it comes to media queries

**Comment by connor4312** [comment]
I don't like the idea of a 16 column grid. 12 divides nicely into halves, thirds, and quarters. 16 columns divides into quarters and halves, but that's it. Want three feature boxes in a row? Sucks.

**Comment by LordFren** [comment]
It has to be modular, not like bootstrap, When you want the simple bootstrap grid, and the grid only it downloads form elements, basic styles, etc. Make it truly modular when delivering it to clients.

**Comment by SevereOverfl0w** [comment]
[$@]gridCols: 12;

**Comment by connor4312** [comment]
Yea we'd probably have grid columns be configurable, like Bootstrap does, but 12 as the default :P

**Comment by SevereOverfl0w** [comment]
Shift grid talk to #4

**Comment by SevereOverfl0w** [comment]
@LordFren any last convincing words for Less before I use Libsass?

**Comment by LordFren** [comment]
http://weknowmemes.com/generator/uploads/generated/g1334313660323648152.jpg

**Comment by SevereOverfl0w** [comment]
I'll take that as a strong no, trust me, you're gonna love Scss!
